# Gunakan image Python yang resmi
FROM python:3.9-slim

# Set working directory di dalam container
WORKDIR /app

# Salin file requirements.txt ke dalam container
COPY requirements.txt .

# Instal dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Salin seluruh kode aplikasi ke dalam container
COPY . .

# Ekspos port aplikasi jika diperlukan
EXPOSE 8000



# Jalankan aplikasi
CMD ["python", "main.py"]
